on:
  workflow_dispatch:
jobs:
  job_1:
    runs_on: ubuntu-latest
    steps:
      - run: "echo job ${{ github.job }}"
  job_2:
    runs_on: ubuntu-latest
    needs: job_1
    steps:
      - run: "echo job ${{ github.job }}"
  job_3:
    runs_on: ubuntu-latest
    needs: job_1
    steps:
      - run: "echo job ${{ github.job }}"
  job_4:
    runs_on: ubuntu-latest
    needs: [job_2,job_3]
    steps:
      - run: "echo job ${{ github.job }}"
