name: Daily Report

on:
  schedule:
    - cron: '30 7 * * *'  # كل يوم الساعة 7:30 صباحًا UTC

jobs:
  report-job:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Report
        run: echo "📊 Generating report on $(date)"

