name: first workflow

on: 
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: print welcome msg
        run: echo "welcome joo"
      - name: checkout repository
        uses: actions/checkout@v4.2.2
      - name: list repo files
        run: ls -la

