on:
  repository_dispatch:
    types: [incident_reports]
    
          

jobs:
  handele_incident:
    runs-on: ubuntu-latest
    steps:
      - name: print incident details
        run: echo "incident reported"
 
